// Run: node --test test/cli.test.mjs
// Covers: real CLI process boundaries, side-effect-free metadata commands,
// argument validation, complete large JSON output, and opt-in upstream JSON.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CLI = fileURLToPath(new URL('../src/cli.mjs', import.meta.url));
const PACKAGE_JSON = fileURLToPath(new URL('../package.json', import.meta.url));
const PACKAGE = JSON.parse(readFileSync(PACKAGE_JSON, 'utf8'));

function makeSandbox(t) {
  const root = mkdtempSync(join(tmpdir(), 'harbor-cli-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const home = join(root, 'home');
  const dshHome = join(root, 'dsh-home');
  mkdirSync(home, { recursive: true });
  mkdirSync(join(dshHome, 'profiles'), { recursive: true });
  return {
    root,
    home,
    dshHome,
    env: {
      ...process.env,
      HOME: home,
      USERPROFILE: home,
      DSH_HOME: dshHome,
    },
  };
}

function runCli(sandbox, args) {
  const result = spawnSync(process.execPath, [CLI, ...args], {
    cwd: dirname(PACKAGE_JSON),
    env: sandbox.env,
    encoding: 'utf8',
    maxBuffer: 5_000_000,
  });
  assert.ifError(result.error);
  return result;
}

function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value)}\n`);
}

function assertTerminalSafe(text, context) {
  // Newlines are generated by the CLI and tabs are explicitly allowed. Every
  // other C0/C1 byte, ESC and DEL must be absent from human-readable output.
  assert.doesNotMatch(text, /[\u0000-\u0008\u000b-\u001f\u007f-\u009f\u2028\u2029]/u, context);
  const bytes = Buffer.from(text, 'utf8');
  for (const byte of [0x1b, 0x07, 0x08, 0x0d, 0x7f]) {
    assert.equal(bytes.includes(byte), false, `${context}: leaked byte 0x${byte.toString(16)}`);
  }
}

test('CLI: --help/-h are side-effect-free and never create a snapshot', (t) => {
  const sandbox = makeSandbox(t);
  for (const args of [['--help'], ['-h'], ['scan', '--help']]) {
    const result = runCli(sandbox, args);
    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /用法:/);
    assert.match(result.stdout, /--check-updates/);
  }
  assert.equal(existsSync(join(sandbox.home, '.config', 'dsh-harbor', 'snapshot.json')), false);
});

test('CLI: --version/-v print package version without scanning', (t) => {
  const sandbox = makeSandbox(t);
  for (const args of [['--version'], ['-v']]) {
    const result = runCli(sandbox, args);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, `${PACKAGE.version}\n`);
  }
  assert.equal(existsSync(join(sandbox.home, '.config', 'dsh-harbor')), false);
});

test('CLI: unknown flags, commands, and extra positionals exit 2 before scanning', (t) => {
  const sandbox = makeSandbox(t);
  const cases = [
    { args: ['scan', '--wat'], message: '未知选项: --wat' },
    { args: ['manifest', '--json'], message: '未知选项: --json' },
    { args: ['unknown-command'], message: '未知命令: unknown-command' },
    { args: ['scan', 'extra'], message: 'scan 不接受位置参数: extra' },
    { args: ['manifest', 'one', 'two'], message: 'manifest 只接受一个目录: one two' },
  ];
  for (const { args, message } of cases) {
    const result = runCli(sandbox, args);
    assert.equal(result.status, 2, `${args.join(' ')}\n${result.stderr}`);
    assert.match(result.stderr, new RegExp(message.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
    assert.match(result.stderr, /用法:/);
  }
  assert.equal(existsSync(join(sandbox.home, '.config', 'dsh-harbor')), false);
});

test('CLI: zero-capability manifest prints a parseable merge object', (t) => {
  const sandbox = makeSandbox(t);
  const pluginDir = join(sandbox.root, 'empty-plugin');
  writeJson(join(pluginDir, 'package.json'), {
    name: 'empty-plugin',
    version: '1.0.0',
    dsh: { bundle: { patch: './cordis.patch.yml' } },
  });

  const result = runCli(sandbox, ['manifest', pluginDir]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /不要覆盖已有的 bundle\/client 等配置/);
  const match = /\n(\{[\s\S]*?\})\n\n逐条核对:/.exec(result.stdout);
  assert.ok(match, result.stdout);
  assert.deepEqual(JSON.parse(match[1]), { capabilities: [] });
  assert.doesNotMatch(match[1], /"dsh"/);
});

test('CLI: empty version drift only claims registry installs are comparable', (t) => {
  const sandbox = makeSandbox(t);
  const profile = join(sandbox.dshHome, 'profiles', 'local');
  const pluginName = 'linked-only-plugin';
  writeJson(join(profile, 'package.json'), {
    name: 'local-profile',
    dependencies: { [pluginName]: 'file:../linked-only-plugin' },
    dsh: { profile: { bundles: [pluginName] } },
  });
  writeJson(join(profile, 'node_modules', pluginName, 'package.json'), {
    name: pluginName,
    version: '9.9.9',
  });

  const result = runCli(sandbox, ['scan', '--no-snapshot']);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /可比较的 registry 安装未发现版本分歧（link\/file 不参与）/);
  assert.doesNotMatch(result.stdout, /各 profile 一致/);

  const checked = runCli(sandbox, ['scan', '--no-snapshot', '--check-updates']);
  assert.equal(checked.status, 0, checked.stderr);
  assert.match(checked.stdout, /本次未联系 registry（本地安装或缓存命中）/);
  assert.doesNotMatch(checked.stdout, /全部为本地安装/);
});

test('CLI: human output strips terminal injection while JSON preserves source data', (t) => {
  const sandbox = makeSandbox(t);
  const profile = join(sandbox.dshHome, 'profiles', 'unsafe');
  const pluginName = 'unsafe-metadata-plugin';
  const pluginDir = join(profile, 'node_modules', pluginName);
  const packagePath = join(pluginDir, 'package.json');
  const injection = '\x1b]0;OWNED\x07\x1b[8mHIDDEN\x1b[0m\rFORGED\nNEXT\u2028ROW\u2029BREAK\u009b31m\x7f';
  const maliciousVersion = `1.0.1-${injection}`;
  const maliciousDescription = `普通 Unicode\t仍保留 ${injection}`;
  const maliciousCapability = `unknown-${injection}`;

  writeJson(join(profile, 'package.json'), {
    name: 'unsafe-profile',
    dependencies: { [pluginName]: '1.0.0' },
    dsh: { profile: { bundles: [pluginName] } },
  });
  writeJson(packagePath, {
    name: pluginName,
    version: '1.0.0',
    description: 'baseline',
  });
  mkdirSync(pluginDir, { recursive: true });
  writeFileSync(join(pluginDir, 'index.mjs'), 'const baseline = process.env.BASELINE;\n');

  // Establish a snapshot so the second process also renders an attacker-owned
  // version inside snapshot change details.
  const baseline = runCli(sandbox, ['scan']);
  assert.equal(baseline.status, 0, baseline.stderr);

  writeJson(packagePath, {
    name: pluginName,
    version: maliciousVersion,
    description: maliciousDescription,
    dsh: { capabilities: [maliciousCapability, { invalid: true }] },
  });
  writeFileSync(join(pluginDir, 'index.mjs'), `const secret = process.env.SECRET; // ${injection}\n`);
  sandbox.env.npm_config_registry = 'http://invalid registry.test';

  const human = runCli(sandbox, ['scan', '--evidence', '--check-updates']);
  assert.equal(human.status, 0, human.stderr);
  assertTerminalSafe(human.stdout, 'stdout');
  assertTerminalSafe(human.stderr, 'stderr');
  assert.match(human.stdout, /普通 Unicode\t仍保留/,
    'ordinary Unicode and tabs should remain readable');
  assert.match(human.stdout, /FORGED NEXT/,
    'attacker newlines should collapse instead of creating forged rows');
  assert.match(human.stdout, /声明格式错误: dsh\.capabilities 必须是字符串数组/);

  const json = runCli(sandbox, ['scan', '--json', '--no-snapshot']);
  assert.equal(json.status, 0, json.stderr);
  const report = JSON.parse(json.stdout);
  assert.equal(report.plugins[0].version, maliciousVersion);
  assert.equal(report.plugins[0].description, maliciousDescription);
  assert.deepEqual(report.plugins[0].declared.declaredCapabilities, [maliciousCapability, { invalid: true }]);
  assert.equal(report.plugins[0].reconciliation.invalidDeclaration.received, 'array');

  const manifestDir = join(sandbox.root, 'unsafe-manifest');
  writeJson(join(manifestDir, 'package.json'), {
    name: `manifest-${injection}`,
    version: '1.0.0',
  });
  const manifest = runCli(sandbox, ['manifest', manifestDir]);
  assert.equal(manifest.status, 0, manifest.stderr);
  assertTerminalSafe(manifest.stdout, 'manifest stdout');
  assertTerminalSafe(manifest.stderr, 'manifest stderr');
});

test('CLI: large --json report is complete and --check-updates is opt-in', (t) => {
  const sandbox = makeSandbox(t);
  const profile = join(sandbox.dshHome, 'profiles', 'default');
  const pluginName = 'large-local-plugin';
  const pluginDir = join(profile, 'node_modules', pluginName);

  writeJson(join(profile, 'package.json'), {
    name: 'default-profile',
    dependencies: { [pluginName]: 'file:../large-local-plugin' },
    dsh: { profile: { bundles: [pluginName] } },
  });
  writeJson(join(pluginDir, 'package.json'), {
    name: pluginName,
    version: '1.2.3',
    // Deliberately exceed a typical 64 KiB pipe buffer. This reproduces the
    // old console.log()+process.exit(0) truncation in a real child process.
    description: 'large-report-payload-'.repeat(10_000),
  });

  const offline = runCli(sandbox, ['scan', '--json', '--no-snapshot']);
  assert.equal(offline.status, 0, offline.stderr);
  assert.ok(Buffer.byteLength(offline.stdout) > 65_536);
  const offlineReport = JSON.parse(offline.stdout);
  assert.equal(offlineReport.plugins[0].description.length, 'large-report-payload-'.length * 10_000);
  assert.equal(Object.hasOwn(offlineReport, 'upstream'), false,
    'default JSON scan must remain offline and omit upstream results');
  assert.equal(existsSync(join(sandbox.home, '.config', 'dsh-harbor')), false,
    '--no-snapshot without --check-updates should write no state');

  const checked = runCli(sandbox, ['scan', '--json', '--no-snapshot', '--check-updates']);
  assert.equal(checked.status, 0, checked.stderr);
  assert.ok(Buffer.byteLength(checked.stdout) > 65_536);
  const checkedReport = JSON.parse(checked.stdout);
  assert.deepEqual(checkedReport.upstream.registryHosts, []);
  assert.equal(checkedReport.upstream.results.length, 1);
  assert.equal(checkedReport.upstream.results[0].status, 'local');
});
